/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Archive } from "./Archive";
import { ArchiveCountArgs } from "./ArchiveCountArgs";
import { ArchiveFindManyArgs } from "./ArchiveFindManyArgs";
import { ArchiveFindUniqueArgs } from "./ArchiveFindUniqueArgs";
import { DeleteArchiveArgs } from "./DeleteArchiveArgs";
import { ArchiveService } from "../archive.service";
@graphql.Resolver(() => Archive)
export class ArchiveResolverBase {
  constructor(protected readonly service: ArchiveService) {}

  async _archivesMeta(
    @graphql.Args() args: ArchiveCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Archive])
  async archives(
    @graphql.Args() args: ArchiveFindManyArgs
  ): Promise<Archive[]> {
    return this.service.archives(args);
  }

  @graphql.Query(() => Archive, { nullable: true })
  async archive(
    @graphql.Args() args: ArchiveFindUniqueArgs
  ): Promise<Archive | null> {
    const result = await this.service.archive(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Archive)
  async deleteArchive(
    @graphql.Args() args: DeleteArchiveArgs
  ): Promise<Archive | null> {
    try {
      return await this.service.deleteArchive(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
