/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Volunteer } from "./Volunteer";
import { VolunteerCountArgs } from "./VolunteerCountArgs";
import { VolunteerFindManyArgs } from "./VolunteerFindManyArgs";
import { VolunteerFindUniqueArgs } from "./VolunteerFindUniqueArgs";
import { DeleteVolunteerArgs } from "./DeleteVolunteerArgs";
import { VolunteerService } from "../volunteer.service";
@graphql.Resolver(() => Volunteer)
export class VolunteerResolverBase {
  constructor(protected readonly service: VolunteerService) {}

  async _volunteersMeta(
    @graphql.Args() args: VolunteerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Volunteer])
  async volunteers(
    @graphql.Args() args: VolunteerFindManyArgs
  ): Promise<Volunteer[]> {
    return this.service.volunteers(args);
  }

  @graphql.Query(() => Volunteer, { nullable: true })
  async volunteer(
    @graphql.Args() args: VolunteerFindUniqueArgs
  ): Promise<Volunteer | null> {
    const result = await this.service.volunteer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Volunteer)
  async deleteVolunteer(
    @graphql.Args() args: DeleteVolunteerArgs
  ): Promise<Volunteer | null> {
    try {
      return await this.service.deleteVolunteer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
