/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Merchandise } from "./Merchandise";
import { MerchandiseCountArgs } from "./MerchandiseCountArgs";
import { MerchandiseFindManyArgs } from "./MerchandiseFindManyArgs";
import { MerchandiseFindUniqueArgs } from "./MerchandiseFindUniqueArgs";
import { DeleteMerchandiseArgs } from "./DeleteMerchandiseArgs";
import { MerchandiseService } from "../merchandise.service";
@graphql.Resolver(() => Merchandise)
export class MerchandiseResolverBase {
  constructor(protected readonly service: MerchandiseService) {}

  async _merchandisesMeta(
    @graphql.Args() args: MerchandiseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Merchandise])
  async merchandises(
    @graphql.Args() args: MerchandiseFindManyArgs
  ): Promise<Merchandise[]> {
    return this.service.merchandises(args);
  }

  @graphql.Query(() => Merchandise, { nullable: true })
  async merchandise(
    @graphql.Args() args: MerchandiseFindUniqueArgs
  ): Promise<Merchandise | null> {
    const result = await this.service.merchandise(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Merchandise)
  async deleteMerchandise(
    @graphql.Args() args: DeleteMerchandiseArgs
  ): Promise<Merchandise | null> {
    try {
      return await this.service.deleteMerchandise(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
